### ISSUE TITLE
error step 1 Gazee

### ISSUE THREAD

**Issue by felipem775** [hubbcaps/gazee#11]
#### Bug Report

OS: What OS are you running Gazee on? Linux mint 17.2
Are you on the latest commit version? Yes, d8432fddfc1dbac963ac4f10e79d4df6f0b2b71e

What is the issue and how do you produce it?
$  python Gazee.py 
  File "Gazee.py", line 194
    cherrypy.engine.timeout_monitor.on: False
                                      ^
SyntaxError: invalid syntax

**Comment by hubbcaps** [comment]
Looks like you're attempting to use python 2 to run it, Gazee requires python 3.6.

Do a python -V and you'll see your system version.

If it is indeed 2, you'll need to install python 3.6, and then explicitly call it like python3 Gazee.py

**Comment by felipem775** [comment]
Oh yes, my fault. Thanks

**Comment by hubbcaps** [comment]
No problem, I make the mistake often with various things. Easily overlooked. Hope you enjoy Gazee!

**Comment by felipem775** [comment]
Perhaps you can change in README when use python -> python3 and pip -> pip3, because a lot of people don't know pip and don't know that it run python2 (depends of configuration).
Sorry for my English

**Comment by hubbcaps** [comment]
That's fair enough. I'll write a sub section in the README about it if python 3 isn't the system default.

Thank you for the suggestion, and no worries on your english, you type it perfectly friend.
