### ISSUE TITLE
missing and failed requirements

### ISSUE THREAD

**Issue by francispeixoto** [hubbcaps/gazee#50]
I follow the install instructions ("sudo pip install requirements.txt")

After a while, the process ended, but when I tried to run gazee, it failed on the cherrypy module import. I ran the module installs manually, and realized that most of them had not installed from the initial command.

After manually installing the requirements from requirements.txt, running gazee failed on these missing module imports, which weren't in the file:

- configparser
- pathlib
- versioning: this module also expects mysql to be installed along with libmysqlclient-dev to satisfy the mysql_config requirement

**Comment by hubbcaps** [comment]
Sounds like you're attempting to use Python 2 to install the requirements, which is likely your system python. Please attempt to use pip3 to install the requirements rather than just pip, if you don't have pip3 available, make sure to install python 3.

**Comment by francispeixoto** [comment]
I made sure to install the requirements with pip3 and I'm running Gazee.py with python3

I'm on an RPi2 with Python 3.4.2 installed along with 2.7.9 installed for mylar

**Comment by hubbcaps** [comment]
Do a pip3 list all for me and post the output.

Configparser is a part of python standard library, so is pathlib, versioning is a gazee specific helper file for git commands, shouldn't have any need for mysql, especially considering the entire program uses sqlite. This means none of these should need to be installed via pip, and if they aren't available for import then python either isn't installed correctly or you are using python 2 as I said above.

Overall, the above sounds like it could be two things:

1. What I said earlier, you are using python 2 and pip 2.

or

2. Whatever OS you are running on the Pi is installing a slimmed down version of python 3 that doesn't include the standard library, which sounds super out there and something I don't think can happen easily, so I err on the side of number one.

Please provide the output I asked for above.

**Comment by francispeixoto** [comment]
pi@raspberrypi:/usr/lib/python3/dist-packages $ pip3 list all
chardet (2.3.0)
cheroot (5.10.0)
CherryPy (12.0.1)
colorama (0.3.2)
gitdb2 (2.0.3)
GitPython (2.1.7)
gpiozero (1.2.0)
html5lib (0.999)
jaraco.classes (1.4.3)
Mako (1.0.7)
MarkupSafe (1.0)
mcpi (0.1.1)
numpy (1.8.2)
patool (1.12)
pgzero (1.1)
picamera (1.10)
pifacecommon (4.2.1)
pifacedigitalio (3.1.0)
pigpio (1.35)
Pillow (2.6.1)
pip (1.5.6)
portend (2.2)
pygame (1.9.2a0)
pyserial (2.6)
python-apt (0.9.3.12)
python-debian (0.1.27)
pytz (2017.3)
rarfile (3.0)
requests (2.4.3)
RPi.GPIO (0.6.3)
RTIMULib (7.2.1)
sense-hat (2.2.0)
setuptools (5.5.1)
six (1.11.0)
smmap2 (2.0.3)
spidev (3.0)
tempora (1.9)
unattended-upgrades (0.1)
urllib3 (1.9.1)
wheel (0.24.0)
xmltodict (0.11.0)
pi@raspberrypi:/usr/lib/python3/dist-packages $

**Comment by hubbcaps** [comment]
This is the contents of the requirements.txt:

CherryPy==11.0.0
Mako==1.0.7
patool==1.12
Pillow==4.2.1
xmltodict==0.11.0
rarfile==3.0
GitPython==2.1.5

You've got Cherrypy 12, not 11, so likely causing the bus error there in the other ticket.

Your pillow is very behind, don't see any evidence this will cause issues though.

Can you do a python3 --version for me as well? 

Have you tried setting up the app and it's requirements in a virtual env so it doesn't have any clashes against system packages?

https://wiki.archlinux.org/index.php/Python/Virtual_environment

**Comment by hubbcaps** [comment]
Also, which OS are you running on the Pi?

**Comment by francispeixoto** [comment]
looks like forcing CherryPy to 11.0.0 did it. Gazee started up. Thanks!

my RPi2 runs python3 v3.4.2 on Raspbian 8

**Comment by hubbcaps** [comment]
Glad that got it going, I appreciate you opening the issue. Wasn't aware CheryPy has updated to 12, so thanks for making me aware. I'll need to see what I can do to support it and what exactly they changed about the engine bus this time around.
