### ISSUE TITLE
cherrypy: AttributeError: 'Bus' object has no attribute 'timeout_monitor'

### ISSUE THREAD

**Issue by francispeixoto** [hubbcaps/gazee#51]
from: python3 Gazee.py

Traceback (most recent call last):
  File "Gazee.py", line 207, in <module>
    main()
  File "Gazee.py", line 194, in main
    cherrypy.engine.timeout_monitor.unsubscribe()
AttributeError: 'Bus' object has no attribute 'timeout_monitor'

**Comment by hubbcaps** [comment]
Sounds like you're attempting to use Python 2 to run Gazee, which is likely your system python. Please attempt to use at least python 3.4 to run Gazee as it states in the readme and in the wiki.

**Comment by francispeixoto** [comment]
I made sure to install the requirements with pip3 and I'm running Gazee.py with python3

I'm on an RPi2 with Python 3.4.2 installed along with 2.7.9 installed for mylar

**Comment by francispeixoto** [comment]
for posterity: in #50 @hubbcaps made me realize that my version of CherryPy was 12.0.0 which generated the error. forcing 11.0.0 did it.
