### ISSUE TITLE
[win10] Internal server error 500 when trying to go to settings page

### ISSUE THREAD

**Issue by Hakker** [hubbcaps/gazee#54]
#### Bug Report

Browser: Firefox 60
OS: Windows 10 with Python 3.6.5
Are you on the latest commit version? Yes

What is the issue and how do you produce it? 
Installed Gazee, I can get on the website yet cannot go to the settings page due to a 500 error. The other 2 pages you can access by default seem to work fine.

**Comment by mccorkled** [comment]
I have this same error on a Synology NAS

**Comment by Forecaster** [comment]
Same issue. `500 Internal Server Error` on win10

**Comment by Otsdarva68** [comment]
I have the same issue on archlinux after cloning the repository. I can access the wepage as well, but get the same 500 error when trying to access settings page. I gave it my comics directory by manually editing data/app.ini, and I could read some books from Recent comics, but couldn't see any books in Library, just the folders.

Python version is 3.7.1

**Comment by nickv2002** [comment]
Same error here with Python 3.6.7 on Ubuntu 18.04. ☹️

**Comment by ruben-kinship** [comment]
anyone had any progress on this?

**Comment by Otsdarva68** [comment]
The developer has said on the wiki that he is no longer actively developing Gazee.

**Comment by ruben-kinship** [comment]
Agreed. Was hoping someone else had found a workaround for it.

**Comment by nelreth** [comment]
To make a small workaround for 500 error You can add one - in file: gazee/versioning.py in function latest_version just add return 'abandoned' and delete the rest - it should looks like this:
```
def latest_version():
    return 'abandoned'

```
There is some problem while fetching last commit from remote repo - but because the project is no longer supported we can omit checking the new version.

**Comment by hubbcaps** [comment]
@MasterOdin was nice enough to whip up a fix for this for ya'll, I've gone ahead and merged it in.
